# Binary star models

ocelot includes a number of models, one of which is a binary star model. Let's look at what it contains, as an example!

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from ocelot.model.binaries import moe_distefano_17

In [2]:
masses, periods = moe_distefano_17.mass, moe_distefano_17.mass_ratio_periods

In [3]:
np.vstack((masses, np.full_like(masses, 2.)))

array([[ 0.1,  0.3,  1. ,  3.5,  7. , 12.5, 16. ],
       [ 2. ,  2. ,  2. ,  2. ,  2. ,  2. ,  2. ]])

In [16]:
moe_distefano_17._get_eccentricity_parameters(masses, np.full_like(masses, 2))

(array([0.1, 0.1, 0.1, 0.3, 0.6, 0.7, 0.7]),
 array([0.92631937, 0.92631937, 0.92631937, 0.92631937, 0.92631937,
        0.92631937, 0.92631937]))

In [33]:
moe_distefano_17._get_mass_ratio_distribution_parameters(masses, np.full_like(masses, 8))

(array([-1.1, -1.1, -1.1, -2. , -2. , -2. , -2. ]),
 array([ 0.3,  0.3,  0.3, -1. , -1.5, -1.5, -1.5]),
 array([0.015, 0.015, 0.015, 0.   , 0.   , 0.   , 0.   ]))